# Generated by Django 4.1.7 on 2023-03-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_conversion_api', '0001_initial'),
        ('pay_app', '0002_user_preferred_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_currency',
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency_conversion_api.currency'),
        ),
    ]
